@startchen
entity member {
}
entity email {
}
entity seminar {
}
entity park_spot {
}

relationship has_email {
}
relationship attends {
}
relationship parks_in {
}
relationship in_charge_of {
}

member -1- has_email
has_email -N- email

member -M- attends
attends -N- seminar

member -1- in_charge_of
in_charge_of -N- seminar

member -1- parks_in
parks_in -1- park_spot

@endchen

